#!/usr/bin/env bash
#'script that displays numbers from 1 to 100.That displays FizzBuzz when the number is a multiple of 3 and 5, displays Fizz when the number is multiple of 3, displays Buzz when the number is a multiple of 5, otherwise, displays the number, in a list format'
i=1
while (( i<=100 ))
do
	if (( i%5==0 )) 
	then 
		echo "Buzz"
	
	elif (( i%3==0 ))
	then
		echo "Fizz"
	
	elif [ $(( i%3==0 )) && $(( i%5==0 )) ]  
	then
		echo "FizzBuzz"

	else 
		echo "$i"
	fi
	(( i++ ))
done
