#!/usr/bin/env bash
#'script that displays, The content of the current directory, in a list format, where only the part of the name after the first dash is displayed'
i="school"
if [ -e "$i" ]
then 
	echo "school file exists"
	if  [ -s "$i" ]
	then 
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$i" ]
	then
		echo "school is a regular file"
	else
		echo " "
	fi
else 
	echo "school file does not exist"
fi
