#!/usr/bin/env bash
#'Script that displays "To infinity and beyond" indefinitely. Requirements:In between each iteration of the loop, add a "sleep 2".'
i=1
while (( i>=0 ))
do
echo "To infinity and beyond"
sleep 2
(( i++ ))
done
