#!/usr/bin/env bash
#'Write a Bash script that displays: "To infinity and beyond" indefinitely, with a "sleep 2" in between each iteration, "I am invincible!!!" when receiving a SIGTERM signal.'
trap "echo 'I am invincible!!!'" 15
i=1
while (( i>=0 ))
do 
echo "To infinity and beyond"
sleep 2
(( i++ ))
done
